use super::*;

pub enum Event {
   KeyPress,
   KeyRelease,
   OwnerGrabButton,
   ButtonPress,
   ButtonRelease,
   EnterWindow,
   LeaveWindow,
   PointerMotion,
   PointerMotionHint,
   Button1Motion,
   Button2Motion,
   Button3Motion,
   Button4Motion,
   Button5Motion,
   ButtonMotion,
   Exposure,
   VisibilityChange,
   StructureNotify,
   ResizeRedirect,
   SubstructureNotify,
   SubstructureRedirect,
   FocusChange,
   PropertyChange,
   ColormapChange,
   KeymapState,
}